### ISSUE TITLE
application.properties except

### ISSUE THREAD

**Issue by bghgu** [tails5555/MyBatis_Practice#1]
application.properties 파일은 DB 정보를 포함해 민감한 정보가 작성되어 있는 파일이니 .gitignore를 이용해 제외하는 것이 좋습니다.

**Comment by tails5555** [comment]
시정하겠습니다. 의견 주셔서 감사합니다.

**Comment by J-minkuk** [comment]
ㅋㅋㅋㅋㅋㅋㅋ이런 ... 사무적인 말투들.....
친해지길 바래.....
